### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by simark** [SNSystems/DIVA#3]
Hi,

Is the source code for DIVA available somewhere, or will it be available?  I was interested in trying to fix #2, but couldn't find any source code in the repository.

I have to say that it was not very obvious that the binaries were only found in the releases tab of github.  I would suggest putting a link at the top of the readme pointing to the latest release, or at least at the releases page.

Simon

**Comment by FlameTop** [comment]
Hello Simon

Regarding the open-sourcing of the DIVA code.

We are working on this internally - watch this space!

Phil Camp

**Comment by FlameTop** [comment]
Hello Simon

Apologies for the delay, but we finally got to push the button :) The source is now available from the master branch.

Regards

Phil

**Comment by simark** [comment]
Awesome! We can close this issue then :).  I'm currently pulling my hair on this DWARF issue

http://lists.dwarfstd.org/pipermail/dwarf-discuss-dwarfstd.org/2017-September/004394.html

so I try DIVA again, see if it presents the info in a more obvious way.
