### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by bjoernbusch** [SNSystems/DIVA#34]
Could you please add some information about the license condition of this product? We need this for the open source clearing process.

**Comment by FreakyDug** [comment]
You can find the license for the Diva source here: https://github.com/SNSystems/DIVA/blob/master/DIVA/LICENSE.txt. 

It's not at the top level because we don't want to make it look like it applies to the External Dependencies directory, because those libraries have their own licenses.

**Comment by bjoernbusch** [comment]
ok, thanks for the clarification.
