### ISSUE TITLE
DIVA does not build with Clang 5.0

### ISSUE THREAD

**Issue by FreakyDug** [SNSystems/DIVA#4]
Clang 5.0 raises lots of warnings, which are treated as errors and cause the build to fail.

See https://travis-ci.org/FreakyDug/DIVA/jobs/275932968.

**Comment by FlameTop** [comment]
Josh submitted changes to fix this.

**Comment by FreakyDug** [comment]
That fixed the problem (though my CI for clang 4 and 5 is now broken for a different reason): https://travis-ci.org/FreakyDug/DIVA/jobs/276053640
